#!/usr/bin/env node
'use strict'
/**
 * Installs SandLoader into whatever attach point this build offers.
 *
 * On **Steam** the game loads a mod loader itself: it scans
 * `steamapps/workshop/content/2764460/<any>/` for a `modinfo.json` whose
 * `modID` is "fluxloader", then requires `fluxloader.bundle.js` beside it.
 * Those two names are the game's ABI, not a dependency on any particular
 * loader project - SandLoader simply occupies the slot. Nothing inside the
 * game directory is touched and a Steam file verification stays green.
 *
 * Sandustry 0.5.6 removed that scan, and on **GOG and other non-Steam builds**
 * it never ran at all. With no slot to occupy the installer renames the
 * original archive aside - `app.asar` to `app.smln-original.asar`, and its
 * `.unpacked` sibling with it - and puts a three-file directory in the name
 * Electron looks at first. No original file's content is modified, and
 * renaming the two paths back is the uninstall. See src/asar/shadow.js for the
 * mechanism and src/asar/platform.js for the honest trade-offs.
 *
 * **Microsoft Store and Game Pass are not supported.** The package lives under
 * WindowsApps, which denies writes even to administrators and verifies its own
 * signature; there is no additive file we may place and no non-destructive way
 * in. The installer says so rather than pretending.
 *
 * The installer also fetches **SteamCMD** once, into `vendor/steamcmd`. That is
 * what makes the manager's "Install from Workshop" button work without a Steam
 * client, and it is the only thing SandLoader downloads: the URL is printed
 * before the fetch, `--no-steamcmd` skips it, a SteamCMD the player already has
 * is used instead of fetching another, and a failed download is a warning
 * rather than a failed install.
 *
 * Usage:
 *   node install.js               install / update
 *   node install.js --no-steamcmd install without fetching SteamCMD
 *   node install.js --steamcmd    fetch SteamCMD only
 *   node install.js --status      report what is currently installed
 *   node install.js --uninstall   remove whatever was installed
 *   node install.js --repair      put a half-applied or orphaned attach right
 */

const fs = require('fs')
const path = require('path')

const locate = require('./src/asar/locate')
const platform = require('./src/asar/platform')
const shadow = require('./src/asar/shadow')
const hostabi = require('./src/asar/hostabi')
const steamcmd = require('./src/mods/steamcmd')
const steamcmdSetup = require('./src/mods/steamcmd-setup')

const SLOT = 'smln'
const BUNDLE = 'fluxloader.bundle.js'
const MODINFO = 'modinfo.json'

function say(...a) { console.log(...a) }

/** The Node binary that is running this file, quoted so the command works when it is not on PATH. */
function rerun(args) {
  const exe = '"' + process.execPath + '"'
  const script = '"' + path.join(__dirname, 'install.js') + '"'
  return exe + ' ' + script + (args ? ' ' + args : '')
}
function fail(msg, hint) {
  console.error('\n  ERROR  ' + msg)
  if (hint) console.error('         ' + String(hint).split('\n').join('\n         '))
  process.exitCode = 1
}

// --------------------------------------------------------------- SteamCMD

/**
 * Fetch SteamCMD unless it is already available or the player opted out.
 *
 * Never fails the install. The loader works fully without it; the only thing
 * missing is the Workshop button, and the message says exactly that so nobody
 * is left guessing why it does nothing.
 */
async function setupSteamcmd(opts = {}) {
  if (opts.skip) {
    say('  steamcmd  skipped (--no-steamcmd)')
    return
  }

  const already = steamcmd.find()
  if (already && !opts.force) {
    say('  steamcmd  ' + already + '  (already installed)')
    return
  }

  say('\n  Fetching SteamCMD - needed for "Install from Workshop".')
  const result = await steamcmdSetup.ensure({ force: opts.force, log: say })

  if (result.ok) {
    say('  steamcmd  ' + result.path)
    return
  }

  // A warning, not an error: everything except the Workshop button still works.
  say('\n  NOTE  SteamCMD could not be fetched: ' + result.error)
  say('        Installing from the Workshop will be unavailable until it is.')
  say('        ' + steamcmd.installHint().split('\n').join('\n        '))
}

// ------------------------------------------------------------- Steam slot

/** The tiny file the game requires. It just points at this checkout. */
function shimSource(entryPath) {
  const target = entryPath.replace(/\\/g, '\\\\')
  return `'use strict'
/*
 * SandLoader slot shim - generated by install.js, do not edit.
 * The real loader lives in the SandLoader project directory referenced below,
 * so editing its sources takes effect on the next launch with no reinstall.
 */
module.exports = require('${target}')
`
}

function modinfoSource(version) {
  return JSON.stringify({
    modID: 'fluxloader',
    name: 'SandLoader',
    shortName: 'SandLoader',
    version,
    description:
      'Mod loader for Sandustry. Occupies the loader slot the game exposes; ' +
      'patches the renderer bundle in memory and never modifies game files.',
    author: 'SandLoader',
  }, null, 2) + '\n'
}

function resolveSlotDir() {
  const dir = locate.workshopDir()
  if (!dir) return null
  return path.join(dir, SLOT)
}

// ------------------------------------------------------- non-Steam bootstrap

/**
 * The stub Electron actually runs. It does nothing but hand over to the
 * checkout, so editing SandLoader's sources needs no reinstall - the same
 * property the Steam shim has.
 */
function bootstrapStub(bootPath) {
  const target = bootPath.replace(/\\/g, '\\\\')
  return `'use strict'
/*
 * SandLoader bootstrap - generated by install.js, do not edit.
 *
 * Electron searches resources/ for 'app.asar' first, and this build does not
 * require that name to be an archive - so this directory is loaded as the
 * application package, and hands control straight back to the real one. The
 * original archive was renamed, never modified; .smln-bootstrap.json beside
 * this file records where it went.
 */
require('${target}').boot({ appDir: __dirname })
`
}

/**
 * `package.json` for the added directory. Mirrors the real app's name and
 * version so anything reading `app.getName()` / `app.getVersion()` still sees
 * the right values.
 */
function bootstrapPackage(realPkg, version) {
  return JSON.stringify({
    name: (realPkg && realPkg.name) || 'sandustry',
    version: (realPkg && realPkg.version) || '0.0.0',
    description: (realPkg && realPkg.description) || 'Sandustry game',
    main: 'smln-bootstrap.js',
    smlnBootstrap: version,
  }, null, 2) + '\n'
}

function receiptSource(install, version, originalArchive) {
  return JSON.stringify({
    loader: 'SandLoader',
    version,
    loaderPath: path.resolve(__dirname),
    installedAt: new Date().toISOString(),
    gameVersion: install.version,
    originalArchive,
    note: 'Uninstall with ' + rerun('--uninstall') + '. No original file was modified; ' +
      'the original archive was renamed to the path in originalArchive.',
  }, null, 2) + '\n'
}

/**
 * Is Sandustry running? Renaming an archive Electron has open fails with
 * EBUSY, and finding that out halfway through the attach is the worst place
 * to find it out. Checked before anything moves, not warned about after.
 */
function gameIsRunning() {
  if (process.platform !== 'win32') return false
  try {
    const out = require('child_process')
      .execFileSync('tasklist', ['/FI', 'IMAGENAME eq Sandustry.exe'], { encoding: 'utf8' })
    return /Sandustry[.]exe/i.test(out)
  } catch (_) {
    // No tasklist, or it failed: do not block the install on a check we could
    // not make. The attach itself still fails safely and rolls back.
    return false
  }
}

/** Read the real app's package.json out of the untouched archive. */
function realPackage(install) {
  try {
    const reader = require('./src/asar/reader')
    const archive = reader.open(install.asar)
    try { return archive.readJson('package.json') } finally { archive.close() }
  } catch (_) { return null }
}

/**
 * SandLoader 0.3 attached by adding `resources/app`, which Electron only
 * reaches when `app.asar` is absent. A Steam update puts `app.asar` back, so
 * that directory is ignored — until something removes `app.asar` again, when
 * it would boot the old loader against the leftover `game.asar`. Move it
 * aside. Only a directory this project wrote is touched.
 *
 * @param {string} resources
 * @returns {string|null} where it went, if it moved
 */
function parkLegacyBootstrap(resources) {
  const legacy = path.join(resources, 'app')
  let isDir = false
  try { isDir = fs.statSync(legacy).isDirectory() } catch (_) { return null }
  if (!isDir) return null

  let ours = fs.existsSync(path.join(legacy, 'smln-bootstrap.js'))
  if (!ours && fs.existsSync(path.join(legacy, 'package.json'))) {
    try {
      const pkg = JSON.parse(fs.readFileSync(path.join(legacy, 'package.json'), 'utf8'))
      ours = !!(pkg && (pkg.smlnBootstrap || pkg.main === 'smln-bootstrap.js'))
    } catch (_) { ours = false }
  }
  if (!ours) return null

  let dest = path.join(resources, 'app.smln-legacy')
  if (fs.existsSync(dest)) dest = path.join(resources, 'app.smln-legacy-' + Date.now())
  fs.renameSync(legacy, dest)
  return dest
}

function installShadow(install, plat, version) {
  if (gameIsRunning()) {
    fail('Sandustry is running.', 'Close the game first - the attach renames files it holds open.')
    return false
  }

  const paths = shadow.derive(plat.resources, plat.base)
  const state = shadow.inspect(plat.resources, plat.base).state

  if (state === 'attached') {
    say('  attach    already installed - reinstalling')
    const back = shadow.revert(plat.resources, plat.base)
    if (!back.ok) { fail('could not remove the previous attach: ' + back.error.message); return false }
  } else if (state !== 'clean') {
    fail('the install is in the "' + state + '" state.', 'Run: ' + rerun('--repair'))
    return false
  }

  // Only when the shadow takes the name Electron searches for. On a
  // game.asar-only layout, resources/app is the live entry point.
  let legacyParked = null
  if (plat.base === 'app') {
    try {
      legacyParked = parkLegacyBootstrap(plat.resources)
    } catch (e) {
      fail('could not move the old resources/app bootstrap aside: ' + e.message)
      return false
    }
  }
  if (legacyParked) {
    say('  legacy    ' + legacyParked)
    say('            the 0.3 resources/app bootstrap was moved aside so Electron')
    say('            cannot boot it against the leftover game.asar')
  }

  const bootPath = path.resolve(__dirname, 'src', 'boot', 'bootstrap.js')
  const out = shadow.apply(plat.resources, plat.base, {
    'package.json': bootstrapPackage(realPackage(install), version),
    'smln-bootstrap.js': bootstrapStub(bootPath),
    [platform.RECEIPT]: receiptSource(install, version, paths.parked),
  })

  if (!out.ok) {
    if (legacyParked) {
      try { fs.renameSync(legacyParked, path.join(plat.resources, 'app')) } catch (_) { /* report the attach error */ }
    }
    const e = out.error
    if (e && (e.code === 'EACCES' || e.code === 'EPERM')) {
      fail('no permission to change the game directory.',
        'Run this terminal as Administrator. Target was:' + String.fromCharCode(10) + paths.slot)
    } else {
      fail('attach failed: ' + (e && e.message), 'The installation was left as it was found.')
    }
    return false
  }

  say('  attach    ' + paths.slot)
  say('  original  ' + paths.parked)
  say('  loader    ' + bootPath)
  say('')
  say("  Installed. No file's content was modified; two paths were renamed.")
  say('  Uninstall with: ' + rerun('--uninstall'))
  say('')
  return true
}

function uninstallShadow(plat) {
  const state = shadow.inspect(plat.resources, plat.base).state
  if (state === 'clean') return false
  if (gameIsRunning()) {
    fail('Sandustry is running.', 'Close the game first - the uninstall renames files it holds open.')
    return false
  }
  const out = shadow.revert(plat.resources, plat.base)
  if (!out.ok) { fail('could not remove the attach: ' + out.error.message); return false }
  say('')
  say('  Removed the attach at ' + shadow.derive(plat.resources, plat.base).slot)
  say('  The game is back to its original files.')
  say('')
  return true
}

/**
 * Put a half-applied or orphaned attach right. Every branch says what it found
 * and what it did; none of them touches the game silently.
 */
function repair() {
  const found = locate.tryLocate()
  if (!found.ok) { fail('could not find Sandustry.'); return }
  const plat = platform.detect(found.install)
  const { state, paths } = shadow.inspect(plat.resources, plat.base)

  say('')
  say('  state     ' + state)
  if (state === 'clean' || state === 'attached') { say('  Nothing to repair.'); say(''); return }

  if (state === 'orphaned') {
    say('  Steam restored ' + paths.slot + '; our copy of the original is an orphan.')
    try { fs.rmSync(paths.parked, { force: true }) } catch (e) { fail('could not remove it: ' + e.message); return }
    try { fs.rmSync(paths.parkedUnpacked, { recursive: true, force: true }) } catch (_) { /* may not exist */ }
    say('  Removed the orphan. Reinstall with: ' + rerun())
    say('')
    return
  }

  if (state === 'parked-only') {
    try {
      fs.renameSync(paths.parked, paths.slot)
      if (fs.existsSync(paths.parkedUnpacked)) fs.renameSync(paths.parkedUnpacked, paths.liveUnpacked)
    } catch (e) { fail('could not put the original back: ' + e.message); return }
    say('  Put the original archive back. Reinstall with: ' + rerun())
    say('')
    return
  }

  if (state === 'broken') {
    fail('the original archive is gone - SandLoader cannot restore it.',
      'Use the Steam client to verify the game files, or reinstall the game, then run:' +
      String.fromCharCode(10) + '  ' + rerun('--uninstall') + ' && ' + rerun())
    return
  }

  fail(paths.slot + ' is a directory SandLoader did not create.',
    'Remove it yourself if you are sure it is no longer needed.')
}

// ------------------------------------------------------------------ status

/**
 * Wraps the attach-point report so the SteamCMD line is printed whichever of
 * its several early returns fired.
 */
function status() {
  attachStatus()
  const exe = steamcmd.find()
  say('  steamcmd  ' + (exe || 'not installed  -  run: ' + rerun('--steamcmd')))
  say('')
}

function attachStatus() {
  const found = locate.tryLocate()
  say('\nSandustry')
  if (found.ok) {
    say('  install   ' + found.install.root)
    say('  version   ' + found.install.version + '  (found via ' + found.install.source + ')')
  } else {
    say('  install   NOT FOUND')
    say('            ' + String(found.error))
    if (found.error.detail && found.error.detail.tried) {
      for (const t of found.error.detail.tried) say('              tried ' + t)
    }
    return
  }

  const plat = platform.detect(found.install)
  const host = hostabi.probe(found.install)
  const strat = platform.strategyFor(plat, host)
  say('\nPlatform')
  for (const line of platform.describe(plat, strat).split('\n')) say('  ' + line)

  say('\nSandLoader')
  say('  Loader slot  : ' + (host.loaderSlot ? 'present' : 'absent') + '  -  ' + host.reason)

  if (strat.id === platform.STRATEGIES.WORKSHOP_SLOT) {
    const slot = resolveSlotDir()
    if (!slot) {
      say('  status    NO STEAM WORKSHOP FOLDER')
      say('            Launch the game once, or create')
      say('            steamapps/workshop/content/' + locate.APP_ID + ' manually.')
      return
    }
    say('  path      ' + slot)
    if (fs.existsSync(path.join(slot, BUNDLE))) {
      say('  status    INSTALLED')
      try {
        const info = JSON.parse(fs.readFileSync(path.join(slot, MODINFO), 'utf8'))
        say('  version   ' + info.version + '  (modID: ' + info.modID + ')')
      } catch (_) { say('  modinfo   unreadable') }
    } else {
      say('  status    not installed')
    }
    return
  }

  if (strat.id === platform.STRATEGIES.SHADOW_ASAR) {
    const { state, paths } = shadow.inspect(plat.resources, plat.base)
    say('  path      ' + paths.slot)
    say('  state     ' + state)
    if (state === 'attached') {
      say('  status    INSTALLED')
      say('  original  ' + paths.parked)
      try {
        const r = JSON.parse(fs.readFileSync(paths.receipt, 'utf8'))
        say('  version   ' + r.version)
        say('  loader    ' + r.loaderPath)
        say('  since     ' + r.installedAt)
      } catch (_) { say('  receipt   unreadable') }
    } else if (state === 'clean') {
      say('  status    not installed')
    } else {
      say('  status    NEEDS REPAIR  -  run: ' + rerun('--repair'))
    }
    return
  }

  say('  status    UNSUPPORTED ON THIS BUILD')
  say('            ' + strat.reason.split('. ').join('.\n            '))
}

// ----------------------------------------------------------------- install

async function install(opts = {}) {
  const found = locate.tryLocate()
  if (!found.ok) {
    fail('could not find Sandustry.', 'Set SANDUSTRY_DIR to the folder containing Sandustry.exe and retry.')
    return
  }
  const pkg = JSON.parse(fs.readFileSync(path.join(__dirname, 'package.json'), 'utf8'))
  say('\n  game      ' + found.install.name + ' ' + found.install.version)
  say('  at        ' + found.install.root)

  const plat = platform.detect(found.install)
  const host = hostabi.probe(found.install)
  const strat = platform.strategyFor(plat, host)
  say('  platform  ' + plat.kind + ' (' + plat.confidence + ')' +
    (plat.evidence.length ? '  -  ' + plat.evidence[0] : ''))

  if (!strat.supported) {
    fail('SandLoader cannot attach to this build.', strat.reason)
    return
  }

  if (strat.id === platform.STRATEGIES.SHADOW_ASAR) {
    say('  attach    ' + strat.id)
    if (!installShadow(found.install, plat, pkg.version)) return
    await setupSteamcmd(opts)
    return
  }

  // --- Steam: the loader slot
  const workshop = locate.workshopDir()
  if (!workshop) {
    fail('no Steam Workshop content folder for app ' + locate.APP_ID + '.',
      'The game only loads a mod loader on Steam. Launch the game once, or create\n' +
      'steamapps/workshop/content/' + locate.APP_ID + ' manually, then retry.')
    return
  }

  const slot = path.join(workshop, SLOT)
  const entry = path.resolve(__dirname, 'src', 'main', 'entry.js')

  try {
    fs.mkdirSync(slot, { recursive: true })
    fs.writeFileSync(path.join(slot, MODINFO), modinfoSource(pkg.version))
    fs.writeFileSync(path.join(slot, BUNDLE), shimSource(entry))
  } catch (e) {
    if (e.code === 'EACCES' || e.code === 'EPERM') {
      fail('no permission to write into the Steam workshop folder.',
        'Run this terminal as Administrator, or move your Steam library out of\n' +
        'Program Files. Target was:\n' + slot)
    } else {
      fail('install failed: ' + e.message)
    }
    return
  }

  say('  slot      ' + slot)
  say('  loader    ' + entry)

  await setupSteamcmd(opts)

  say('\n  Installed. Start Sandustry and press ^ (or F1) to open the console.')
  say('  Nothing in the game directory was modified.\n')
}

function uninstall() {
  const found = locate.tryLocate()
  let removed = false

  const slot = resolveSlotDir()
  if (slot && fs.existsSync(slot)) {
    try {
      fs.rmSync(slot, { recursive: true, force: true })
      say('\n  Removed ' + slot)
      removed = true
    } catch (e) {
      fail('could not remove ' + slot + ': ' + e.message)
    }
  }

  if (found.ok) {
    const plat = platform.detect(found.install)
    if (uninstallShadow(plat)) removed = true
  }

  // Only the copy the installer fetched. A SteamCMD the player installed
  // themselves is theirs and is left exactly where it is.
  if (steamcmdSetup.remove()) {
    say('  Removed ' + steamcmdSetup.vendorDir())
    removed = true
  }

  if (!removed) say('\n  Nothing to remove.\n')
}

const argv = process.argv.slice(2)
const has = (...names) => names.some((n) => argv.includes(n))

if (has('--status', '-s')) status()
else if (has('--repair')) repair()
else if (has('--uninstall', '-u')) uninstall()
else if (has('--steamcmd')) {
  // Re-run just the fetch, for a player who declined it first time or whose
  // download failed. --force replaces a copy we fetched before.
  setupSteamcmd({ force: has('--force') }).catch((e) => fail('SteamCMD setup failed: ' + e.message))
} else {
  install({ skip: has('--no-steamcmd'), force: has('--force') })
    .catch((e) => fail('install failed: ' + e.message))
}
